# .github/workflows/dev_pipeline.yml
name: Dev Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/common_pipeline.yml
    with:
      env_name: dev
      working_dir: env/dev
      terraform_state_key: "terraform_dev.tfstate"
    secrets:
      AZURE_CREDENTIAL: ${{ secrets.AZURE_CREDENTIAL }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
